import type { CrmBaseRecord, Lead, LeadPlatform, PreferredChannel } from './types';

const now = '2026-06-11T09:00:00.000Z';

const preferredChannelByPlatform: Record<LeadPlatform, PreferredChannel> = {
  Upwork: 'upwork',
  Instagram: 'instagram',
  LinkedIn: 'website',
  Referral: 'email',
  Website: 'website',
  Manual: 'email',
  Other: 'email',
  Facebook: 'facebook',
  WhatsApp: 'whatsapp',
  Gmail: 'gmail',
  'Google Contacts': 'email',
  Behance: 'behance',
  Pinterest: 'website',
  Dribbble: 'dribbble',
  YouTube: 'youtube',
  'Portfolio Website': 'website'
};

const sourceByPlatform: Record<LeadPlatform, CrmBaseRecord['source']> = {
  Upwork: 'upwork',
  Instagram: 'instagram',
  LinkedIn: 'manual',
  Referral: 'manual',
  Website: 'portfolio_website',
  Manual: 'manual',
  Other: 'manual',
  Facebook: 'facebook',
  WhatsApp: 'whatsapp',
  Gmail: 'gmail',
  'Google Contacts': 'google_contacts',
  Behance: 'behance',
  Pinterest: 'pinterest',
  Dribbble: 'dribbble',
  YouTube: 'youtube',
  'Portfolio Website': 'portfolio_website'
};

const leadBase = (lead: Omit<Lead, keyof CrmBaseRecord> & Partial<CrmBaseRecord>): Lead => ({
  id: lead.id || `lead-${Date.now()}`,
  source: lead.source || sourceByPlatform[lead.platform],
  sourceId: lead.sourceId,
  createdAt: lead.createdAt || now,
  updatedAt: lead.updatedAt || now,
  lastContactedAt: lead.lastContactedAt,
  nextFollowUpAt: lead.nextFollowUpAt,
  status: lead.status || 'New',
  tags: lead.tags || [],
  notes: lead.notes || '',
  aiSummary: lead.aiSummary || '',
  aiScore: lead.aiScore || 50,
  consentStatus: lead.consentStatus || 'unknown',
  preferredChannel: lead.preferredChannel || preferredChannelByPlatform[lead.platform],
  interactionHistory: lead.interactionHistory || [],
  name: lead.name,
  platform: lead.platform,
  stage: lead.stage,
  email: lead.email,
  phoneOrHandle: lead.phoneOrHandle,
  contactId: lead.contactId,
  companyId: lead.companyId,
  serviceInterest: lead.serviceInterest,
  budgetRange: lead.budgetRange,
  temperature: lead.temperature,
  nextBestAction: lead.nextBestAction
});

export const crmSeedLeads: Lead[] = [
  leadBase({
    id: 'lead-rezbook',
    name: 'Lina Haddad',
    platform: 'Gmail',
    email: 'lina@rezbook.com',
    phoneOrHandle: '+962 78 220 4433',
    status: 'Hot',
    serviceInterest: 'Brand Video',
    budgetRange: '$3,000 - $5,000',
    lastContactedAt: '2026-06-10',
    nextFollowUpAt: '2026-06-12',
    notes: 'Asked for revised timeline, final price, and retainer option for launch month assets.',
    aiScore: 94,
    nextBestAction: 'Send revised proposal with monthly motion retainer option.',
    temperature: 'Hot',
    aiSummary: 'Urgent buying intent with clear launch use case. Lead with timeline certainty and a retainer path.',
    tags: ['saas', 'launch', 'retainer']
  }),
  leadBase({
    id: 'lead-north-pixel',
    name: 'Omar Khaled',
    platform: 'Behance',
    email: 'omar@northpixel.co',
    phoneOrHandle: '@northpixel',
    status: 'Warm',
    serviceInterest: 'Logo Animation',
    budgetRange: '$1,500 - $3,000',
    lastContactedAt: '2026-06-09',
    nextFollowUpAt: '2026-06-13',
    notes: 'Wants a premium 3D logo reveal and asked for reel examples with metallic/glass looks.',
    aiScore: 88,
    nextBestAction: 'Send a short reel with 3 similar logo reveals and a two-tier price anchor.',
    temperature: 'Hot',
    aiSummary: 'Strong portfolio-fit lead. Keep message visual and push toward a paid concept frame.',
    tags: ['agency', '3d', 'logo']
  }),
  leadBase({
    id: 'lead-amana',
    name: 'Ahmad Naser',
    platform: 'Instagram',
    email: 'ahmad@amana.studio',
    phoneOrHandle: '@amana.studio',
    status: 'Warm',
    serviceInterest: 'Social Media Ads',
    budgetRange: '$750 - $1,500',
    lastContactedAt: '2026-06-08',
    nextFollowUpAt: '2026-06-11',
    notes: 'Launch campaign needs kinetic typography for Instagram stories and square feed cuts.',
    aiScore: 81,
    nextBestAction: 'Ask for launch date and send three package options.',
    temperature: 'Warm',
    aiSummary: 'Medium budget with real timeline signal. Qualify deadline before custom proposal work.',
    tags: ['instagram', 'ads', 'launch']
  }),
  leadBase({
    id: 'lead-upwork-logo',
    name: 'Harper Quinn',
    platform: 'Upwork',
    email: 'harper@quinnmedia.com',
    phoneOrHandle: 'Upwork: HarperQ',
    status: 'New',
    serviceInterest: 'YouTube Intro',
    budgetRange: '$500 - $750',
    lastContactedAt: '2026-06-10',
    nextFollowUpAt: '2026-06-11',
    notes: 'Tech creator needs a fast intro and channel transition pack. Job post mentioned clean, premium, not flashy.',
    aiScore: 73,
    nextBestAction: 'Submit a concise proposal with one intro example and a 5-day delivery plan.',
    temperature: 'Warm',
    aiSummary: 'Good fit if scope stays tight. Avoid unlimited revisions and offer add-ons separately.',
    tags: ['upwork', 'youtube']
  }),
  leadBase({
    id: 'lead-whatsapp-fitness',
    name: 'Maya Salim',
    platform: 'WhatsApp',
    email: 'maya@orbitfit.jo',
    phoneOrHandle: '+962 79 441 8820',
    status: 'Cold',
    serviceInterest: 'Social Media Ads',
    budgetRange: '$250 - $500',
    lastContactedAt: '2026-06-04',
    nextFollowUpAt: '2026-06-14',
    notes: 'Interested in short product ads but budget is unclear and decision-maker is not confirmed.',
    aiScore: 49,
    nextBestAction: 'Send a qualifying question about monthly ad volume before proposing.',
    temperature: 'Cold',
    aiSummary: 'Do not over-invest yet. Confirm budget, ad count, and approval owner first.',
    tags: ['fitness', 'qualification']
  }),
  leadBase({
    id: 'lead-portfolio-rami',
    name: 'Rami Darwish',
    platform: 'Portfolio Website',
    email: 'hello@ramidarwish.com',
    phoneOrHandle: 'portfolio form',
    status: 'New',
    serviceInterest: 'Motion Design',
    budgetRange: '$1,500 - $3,000',
    lastContactedAt: '2026-06-11',
    nextFollowUpAt: '2026-06-12',
    notes: 'Submitted portfolio form after viewing the cyberpunk intro case study.',
    aiScore: 86,
    nextBestAction: 'Reply with discovery call slots and ask what references made them reach out.',
    temperature: 'Hot',
    aiSummary: 'Inbound portfolio lead with high intent. Reference the exact case study they viewed and move fast.',
    tags: ['inbound', 'portfolio']
  }),
  leadBase({
    id: 'lead-youtube-dima',
    name: 'Dima Al-Far',
    platform: 'YouTube',
    email: 'dima@creatorlab.jo',
    phoneOrHandle: '@dima.creatorlab',
    status: 'Hot',
    serviceInterest: 'YouTube Intro',
    budgetRange: '$750 - $1,500',
    lastContactedAt: '2026-06-11',
    nextFollowUpAt: '2026-06-12',
    notes: 'Creator wants a new intro, lower thirds, subscribe bumper, and animated transition pack before a channel relaunch.',
    aiScore: 89,
    nextBestAction: 'Send a compact channel motion package with intro, bumper, and transition options.',
    temperature: 'Hot',
    aiSummary: 'Strong fit with urgent launch timeline. Bundle recurring channel assets to raise deal value.',
    tags: ['youtube', 'creator', 'intro']
  }),
  leadBase({
    id: 'lead-logo-nour',
    name: 'Nour Alami',
    platform: 'Dribbble',
    email: 'nour@pixelbay.studio',
    phoneOrHandle: '@pixelbay',
    status: 'Warm',
    serviceInterest: 'Logo Animation',
    budgetRange: '$1,500 - $3,000',
    lastContactedAt: '2026-06-10',
    nextFollowUpAt: '2026-06-13',
    notes: 'Studio asked for a flexible logo animation system that can work in reels, presentations, and pitch decks.',
    aiScore: 84,
    nextBestAction: 'Reply with a modular logo animation proposal and two visual directions.',
    temperature: 'Warm',
    aiSummary: 'Good agency lead. Position it as a reusable motion identity kit, not a single animation.',
    tags: ['logo animation', 'studio', 'identity']
  }),
  leadBase({
    id: 'lead-ig-sara',
    name: 'Sara Mansour',
    platform: 'Instagram',
    email: 'sara@glowline.co',
    phoneOrHandle: '@glowline.co',
    status: 'New',
    serviceInterest: 'Social Media Ads',
    budgetRange: '$500 - $750',
    lastContactedAt: '2026-06-12',
    nextFollowUpAt: '2026-06-12',
    notes: 'Asked in DMs about animated Instagram ad variations for a skincare launch. Needs Arabic and English captions.',
    aiScore: 76,
    nextBestAction: 'Ask for launch date, product assets, and number of ad variations needed.',
    temperature: 'Warm',
    aiSummary: 'Useful social ad lead with bilingual need. Qualify assets and deadline before pricing.',
    tags: ['instagram ads', 'arabic english', 'beauty']
  })
];
