import type { ContentItem } from './types';

export const contentSeedItems: ContentItem[] = [
  {
    id: 'content-ig-neon-reel',
    source: 'manual',
    date: '2026-06-12',
    scheduledDate: '2026-06-12',
    platform: 'Instagram',
    contentType: 'Reel',
    title: 'Before and after kinetic type polish',
    idea: 'Show the visual difference between rough timing and polished motion.',
    hook: 'Two timing changes made this type animation feel 10x sharper.',
    script: 'Open with rough version, show final version, explain two changes, close with CTA.',
    caption: 'A quick before/after of how timing, easing, and contrast turn plain typography into a sharper launch moment.',
    hashtags: ['#motiondesign', '#kinetictype', '#aftereffects'],
    status: 'Waiting Approval',
    relatedProject: 'Neon Shift',
    relatedGoal: 'Finish the Neon Shift visual system',
    cta: 'DM for motion direction',
    performanceMetrics: ['Target 8% watch-through', 'Target 3 qualified DMs'],
    aiNotes: 'Strong hook. Needs final export approval before publishing.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z'
  },
  {
    id: 'content-youtube-c4d',
    source: 'manual',
    date: '2026-06-14',
    scheduledDate: '2026-06-14',
    platform: 'YouTube',
    contentType: 'YouTube Short',
    title: '3 C4D lighting tricks for premium intros',
    idea: 'Teach one practical visual lesson from a real project.',
    hook: 'Three tiny lighting choices make intros feel more expensive.',
    script: 'Hook, three examples, quick final comparison, CTA.',
    caption: 'Three tiny lighting choices that make a motion intro feel more expensive in the first five seconds.',
    hashtags: ['#shorts', '#cinema4d', '#motiondesign'],
    status: 'Draft',
    relatedProject: 'Neon Shift',
    relatedGoal: 'Build an independent creator business',
    cta: 'Subscribe for motion process clips',
    performanceMetrics: ['Target 65% retention at 10s'],
    aiNotes: 'Cut fast. Use captions on every beat.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z'
  },
  {
    id: 'content-behance-rezbook',
    source: 'manual',
    date: '2026-06-17',
    scheduledDate: '2026-06-18',
    platform: 'Behance',
    contentType: 'Behance Project',
    title: 'RezBook product motion system',
    idea: 'Turn product motion into a client-facing case study.',
    hook: 'This motion system was built to make onboarding clearer before it made the UI prettier.',
    script: 'Explain business problem, show product moments, finish with reusable system angle.',
    caption: 'A case study on using UI motion to make product onboarding feel clearer and more premium.',
    hashtags: ['#behance', '#productmotion', '#saas'],
    status: 'Backlog',
    relatedProject: 'RezBook UI Motion Pack',
    relatedGoal: 'Reach $120k annual creative revenue',
    cta: 'View full case study',
    performanceMetrics: ['Target 2 inbound leads from case study'],
    aiNotes: 'Needs metrics and testimonial before approval.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z'
  },
  {
    id: 'content-linkedin-motion-post',
    source: 'manual',
    date: '2026-06-18',
    scheduledDate: '2026-06-18',
    platform: 'LinkedIn',
    contentType: 'Post',
    title: 'Why launch motion needs business clarity, not just polish',
    idea: 'Position motion design as a business tool for founders and teams.',
    hook: 'The strongest motion posts are not the flashiest ones. They are the clearest.',
    script: 'State the problem, explain the commercial angle, give one practical takeaway, CTA.',
    caption: 'Motion direction works better when it clarifies value, not just aesthetics.',
    hashtags: ['#motiondesign', '#branding', '#creativebusiness'],
    status: 'Scheduled',
    relatedProject: 'RezBook UI Motion Pack',
    relatedGoal: 'Reach $120k annual creative revenue',
    cta: 'Send a message if you want a tailored version',
    aiNotes: 'Scheduled manually. Keep tone founder-facing.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z',
    approvedAt: '2026-06-10T12:00:00.000Z'
  },
  {
    id: 'content-pinterest-moodboard',
    source: 'manual',
    date: '2026-06-18',
    scheduledDate: '2026-06-19',
    platform: 'Pinterest',
    contentType: 'Pin',
    title: 'Premium motion direction moodboard',
    idea: 'Use a moodboard pin as top-of-funnel inspiration content.',
    hook: 'A moodboard can sell direction before the animation exists.',
    script: 'Static/motion reference pin with short CTA.',
    caption: 'Motion design references for polished launch visuals, kinetic type, and premium product animations.',
    hashtags: ['#designinspiration', '#motiongraphics', '#branding'],
    status: 'Backlog',
    relatedProject: 'Zenith Brand Motion',
    relatedGoal: 'Build an independent creator business',
    cta: 'Save this visual direction',
    performanceMetrics: ['Target 15 saves'],
    aiNotes: 'Ready once pin image is exported.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z'
  },
  {
    id: 'content-dribbble-logo',
    source: 'manual',
    date: '2026-06-19',
    scheduledDate: '2026-06-20',
    platform: 'Dribbble',
    contentType: 'Dribbble Shot',
    title: 'North Pixel logo reveal hero frame',
    idea: 'Single-frame proof for premium logo motion.',
    hook: 'The hero frame often decides whether someone watches the loop.',
    script: 'Static shot + short context.',
    caption: 'A polished 3D logo reveal frame built around metallic depth, reflection, and clean timing.',
    hashtags: ['#dribbble', '#logomotion', '#3d'],
    status: 'Draft',
    relatedProject: 'North Pixel Logo Reveal',
    relatedGoal: 'Reach $120k annual creative revenue',
    cta: 'See the motion loop',
    performanceMetrics: ['Target 500 views'],
    aiNotes: 'Needs 4:3 shot crop.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z'
  },
  {
    id: 'content-portfolio-case-study',
    source: 'manual',
    date: '2026-06-21',
    scheduledDate: '2026-06-21',
    platform: 'Portfolio Website',
    contentType: 'Case Study',
    title: 'Zenith brand motion case study',
    idea: 'Long-form proof page for sales and outreach.',
    hook: 'A strong case study should explain the commercial result, not just the visuals.',
    script: 'Problem, solution, metrics, CTA.',
    caption: 'How a brand motion package creates a more memorable launch system across web and social.',
    hashtags: ['#portfolio', '#casestudy', '#brandmotion'],
    status: 'Published',
    relatedProject: 'Zenith Brand Motion',
    relatedGoal: 'Build an independent creator business',
    cta: 'Book a project call',
    publishedUrl: 'https://example.com/zenith-case-study',
    performanceMetrics: ['3 inbound inquiries', 'Time on page: 2m 10s'],
    aiNotes: 'Published manually. Future CMS adapter can sync status.',
    createdAt: '2026-06-10T09:00:00.000Z',
    updatedAt: '2026-06-10T09:00:00.000Z',
    publishedAt: '2026-06-11T08:00:00.000Z'
  }
];
