export { requiredXpForLevel, levelFromXp, currentLevelXp, xpToNextLevel, levelTitle, levelProgressPercent } from './levelEngine';
export type { XpCategory, XpBreakdown } from './xpEngine';
export { habitXp, questXp, exposureStepXp, resistBadGuyXp, powerUpXp, ifThenXp, contractXp, reflectionXp, recoveryActionXp, integrityBonusXp, isContentMeaningful, HABIT_XP_BY_DIFFICULTY, QUEST_BASE_XP } from './xpEngine';
export type { TraitScoreInput, TraitScoreResult } from './traitEngine';
export { calculateTraitScore, selectBestTraits, traitXpToNextLevel, traitGrowthRate } from './traitEngine';
export type { StreakState, WeeklyConsistency } from './streakEngine';
export { calculateStreak, weeklyConsistency, isOnStreak, daysSinceLastCompletion, missedDayNote, GRACE_TOKENS_PER_WEEK } from './streakEngine';
export type { StepAdvancementInput, StepAdvancementResult, StepSuggestion } from './exposureEngine';
export { canAdvanceStep, suggestStepModification, shouldReturnToPreviousStep, computeLadderProgress, validateSuccess } from './exposureEngine';
export type { AdaptiveInput, AdaptiveSuggestion } from './adaptiveEngine';
export { getAdaptiveSuggestions, filterForRecoveryMode } from './adaptiveEngine';
export type { AchievementDefinition, AchievementCheckState } from './achievementEngine';
export { ACHIEVEMENT_DEFINITIONS, checkNewAchievements } from './achievementEngine';
export type { RecoveryState, RecoveryAction } from './recoveryEngine';
export { getRecoveryState, canToggleRecovery, getRecoveryDailyTarget, isEligibleForRecoveryXp } from './recoveryEngine';
export type { BadGuyEncounter, BadGuyPattern } from './badGuyEngine';
export { buildEncounter, analyzePatterns, getRecoverySuggestion } from './badGuyEngine';
export type { TitleSuggestion } from './titleEngine';
export { getLevelTitle, suggestTitles, generateCustomTitle } from './titleEngine';
