import type { PortfolioPlatform, PortfolioProject } from './types';

const platforms: PortfolioPlatform[] = ['Behance', 'Dribbble', 'Pinterest', 'YouTube', 'Instagram', 'Facebook', 'Personal Website'];

const statusFor = (published: PortfolioPlatform[] = []) => platforms.map(platform => ({
  platform,
  status: published.includes(platform) ? 'Published' as const : 'Draft' as const,
  url: published.includes(platform) ? `https://example.com/${platform.toLowerCase().replace(' ', '-')}` : undefined,
  updatedAt: '2026-06-11'
}));

export const portfolioSeedProjects: PortfolioProject[] = [
  {
    id: 'portfolio-neon-shift',
    projectTitle: 'Neon Shift Cyberpunk Intro',
    title: 'Neon Shift Cyberpunk Intro',
    clientName: 'Aether Interactive',
    client: 'Aether Interactive',
    industry: 'Gaming / Entertainment',
    category: '3D Motion Intro',
    description: 'A premium cyberpunk intro sequence built with holographic typography, emissive shaders, and fast editorial rhythm.',
    problem: 'The client needed a memorable opening identity that made a podcast channel feel premium in the first five seconds.',
    solution: 'Built a cinematic motion system with neon lighting, kinetic type, glass materials, and audio-synced transitions.',
    toolsUsed: ['Cinema 4D', 'Octane', 'After Effects', 'Premiere Pro'],
    finalLinks: ['https://example.com/neon-shift-final.mp4'],
    links: ['https://example.com/neon-shift-final.mp4'],
    thumbnail: 'Neon_Intro_Thumbnail.jpg',
    thumbnailUrl: 'Neon_Intro_Thumbnail.jpg',
    status: 'published',
    caseStudyText: 'A high-energy intro system designed to make the brand feel sharper, faster, and more cinematic.',
    servicesProvided: ['Creative direction', '3D animation', 'Compositing', 'Sound sync'],
    deliverables: ['Creative direction', '3D animation', 'Compositing', 'Sound sync'],
    resultsMetrics: ['Improved intro retention', 'Created reusable channel identity', 'Delivered social cutdowns'],
    tags: ['cyberpunk', '3d', 'intro', 'motion design'],
    bestFor: ['motion design', 'brand video', 'game dev', 'freelance proof'],
    linkedLeadIds: [],
    linkedJobIds: ['job-company-game-prototype'],
    linkedDraftIds: [],
    publishStatus: statusFor(['Instagram', 'Dribbble']),
    createdAt: '2026-06-01T09:00:00.000Z',
    updatedAt: '2026-06-11T09:00:00.000Z'
  },
  {
    id: 'portfolio-rezbook',
    projectTitle: 'RezBook UI Motion Pack',
    title: 'RezBook UI Motion Pack',
    clientName: 'RezBook SaaS',
    client: 'RezBook SaaS',
    industry: 'SaaS / Product',
    category: 'Product Motion',
    description: 'A motion system for onboarding screens, feature reveals, and launch assets for a booking SaaS product.',
    problem: 'The product had strong UI but needed motion to clarify features and make launch materials more engaging.',
    solution: 'Created UI transitions, product feature loops, and short launch videos optimized for website and social.',
    toolsUsed: ['After Effects', 'Figma', 'Rive', 'Premiere Pro'],
    finalLinks: ['https://example.com/rezbook-motion.mp4'],
    links: ['https://example.com/rezbook-motion.mp4'],
    thumbnail: 'RezBook_UI_Motion_Cover.jpg',
    thumbnailUrl: 'RezBook_UI_Motion_Cover.jpg',
    status: 'ready',
    caseStudyText: 'A product motion system designed to turn interface clarity into stronger launch communication.',
    servicesProvided: ['UI motion', 'Product video', 'Launch cutdowns'],
    deliverables: ['UI motion', 'Product video', 'Launch cutdowns'],
    resultsMetrics: ['Clearer onboarding story', 'Reusable motion components', 'Launch-ready social clips'],
    tags: ['saas', 'ui motion', 'product video'],
    bestFor: ['product launch', 'motion design', 'freelance proof'],
    linkedLeadIds: ['lead-rezbook'],
    linkedJobIds: ['job-remoteok-motion-artist'],
    linkedDraftIds: [],
    publishStatus: statusFor(['Personal Website']),
    createdAt: '2026-06-05T09:00:00.000Z',
    updatedAt: '2026-06-11T09:00:00.000Z'
  },
  {
    id: 'portfolio-glowline-ads',
    projectTitle: 'Glowline Instagram Ad Motion Kit',
    title: 'Glowline Instagram Ad Motion Kit',
    clientName: 'Glowline Beauty',
    client: 'Glowline Beauty',
    industry: 'Beauty / Ecommerce',
    category: 'Social Ad Animation',
    description: 'A compact ad motion system with bilingual Arabic/English kinetic typography, product closeups, and modular story/feed exports.',
    problem: 'The launch needed premium product movement across multiple ad placements without making every creative from scratch.',
    solution: 'Built reusable motion templates, color-coded product scenes, and export-ready variations for feed, story, and reels.',
    toolsUsed: ['After Effects', 'Photoshop', 'Premiere Pro', 'Figma'],
    finalLinks: ['https://example.com/glowline-ad-kit.mp4'],
    links: ['https://example.com/glowline-ad-kit.mp4'],
    thumbnail: 'Glowline_Ad_Motion_Kit.jpg',
    thumbnailUrl: 'Glowline_Ad_Motion_Kit.jpg',
    status: 'published',
    caseStudyText: 'A fast-turnaround launch kit designed to turn product assets into polished paid-social motion.',
    servicesProvided: ['Ad animation', 'Kinetic typography', 'Bilingual exports', 'Creative direction'],
    deliverables: ['Ad animation', 'Kinetic typography', 'Bilingual exports', 'Creative direction'],
    resultsMetrics: ['6 ad variations delivered', 'Arabic and English cutdowns', 'Reusable template system'],
    tags: ['instagram ads', 'beauty', 'bilingual', 'paid social'],
    bestFor: ['social ads', 'brand video', 'motion design'],
    linkedLeadIds: ['lead-ig-sara'],
    linkedJobIds: [],
    linkedDraftIds: [],
    publishStatus: statusFor(['Instagram', 'Personal Website']),
    createdAt: '2026-06-09T09:00:00.000Z',
    updatedAt: '2026-06-12T09:00:00.000Z'
  }
];
